### ISSUE TITLE
Install fails to pull rsync patch

### ISSUE THREAD

**Issue by olcrazypete** [jedda/Counterpart#10]
Running 'brew install counterpart' fails with downloading the rsync patch with curl: (56) error.  

Possible movement of the patch on the git.samba.org site, wget of the url fails as well.

![screenshot 2015-02-23 08 51 00](https://cloud.githubusercontent.com/assets/11159981/6328810/2561a850-bb39-11e4-84bc-7dfbc3b0d117.png)

**Comment by shamrt** [comment]
Can confirm. I get the following:

    $ brew install counterpart
    ==> Reinstalling counterpart
    ######################################################################## 100.0%
    ==> Installing counterpart dependency: https://raw.github.com/Homebrew/homebrew-dupes/109dca908c6499116e07483d7afe8a1c3ef63
    ==> Downloading http://rsync.samba.org/ftp/rsync/src/rsync-3.0.9.tar.gz
    Already downloaded: /Library/Caches/Homebrew/rsync-3.0.9.tar.gz
    ==> Downloading http://gitweb.samba.org/?p=rsync-patches.git;a=blob_plain;hb=v3.0.9;f=fileflags.diff
    ######################################################################## 100.0%
    curl: (18) transfer closed with outstanding read data remaining
    Error: Failed to download resource "rsync--patch"
    Download failed: http://gitweb.samba.org/?p=rsync-patches.git;a=blob_plain;hb=v3.0.9;f=fileflags.diff

**Comment by habermeier** [comment]
Same here:
==> Installing counterpart from jedda/homebrew-counterpart
######################################################################## 100.0%
==> Installing jedda/counterpart/counterpart dependency: https://raw.github.com/Homebrew/homebrew-dupes/109dca908c6499116e07483d7afe8a1c3ef63ad6/rsync.rb
==> Downloading http://rsync.samba.org/ftp/rsync/src/rsync-3.0.9.tar.gz
Already downloaded: /Library/Caches/Homebrew/rsync-3.0.9.tar.gz
==> Downloading http://gitweb.samba.org/?p=rsync-patches.git;a=blob_plain;hb=v3.0.9;f=fileflags.diff
######################################################################## 100.0%
curl: (18) transfer closed with outstanding read data remaining
Error: Failed to download resource "rsync--patch"
Download failed: http://gitweb.samba.org/?p=rsync-patches.git;a=blob_plain;hb=v3.0.9;f=fileflags.diff

**Comment by AlexanderWillner** [comment]
Similar to #16. My current way to install counterpart: https://github.com/AlexanderWillner/Counterpart
