### ISSUE TITLE
rsync error: rename "[...]CoreServices/.boot.efi.DtQLrN" -> "[...]/CoreServices/boot.efi": Operation not permitted

### ISSUE THREAD

**Issue by VitosX** [jedda/Counterpart#17]
"/System/Library/CoreServices/boot.efi" system file has _locked_ attribute, therefore only first backup is performed properly. Subsequent rsync launches cannot update the backup copy of this file. Manual `chflags nouchg` on this file is needed every time before launching counterpart.

**Comment by AlexanderWillner** [comment]
Probably not the case anymore?
```
$ sudo find /System/Library/CoreServices/ -flags uchg
$
```

**Comment by VitosX** [comment]
Indeed. I checked macOS 10.11.6, 10.12.6 and 10.13.3, they are fine. Only older OSes still have boot.efi locked.
