### ISSUE TITLE
How do you install  manually?

### ISSUE THREAD

**Issue by wdonno** [jedda/Counterpart#18]
Since this appears to be abandoned, could someone say how to install manually?

**Comment by shoopdawoop** [comment]
You simply copy the script and use it on the drive or folder you want to backup, e.g.

`/usr/local/bin/counterpart.sh -s "/Volumes/MyHarddrrive" -d "/Volumes/MyBackupDrive" -e "/etc/counterpart_exclude" -b thepassword`

**Comment by AlexanderWillner** [comment]
See https://github.com/alexanderwillner/counterpart
