### ISSUE TITLE
odd 'read errors mapping' error

### ISSUE THREAD

**Issue by shoopdawoop** [jedda/Counterpart#7]
I thought this might be of interest:

I had to put `Mobile*Documents*` on my exclusion list as I encountered an error while backing up a Mac OS X 10.9.2 Server to an external drive (both HFS+).

I suspect the reason might be a directory name in the path that contains a '=' character at the end, but I have not really tested this.
At first I simply deleted the whole directory hoping that if it would be recreated I might end up with a different directory name, but the same one reappeared. I figured these files are probably not important to me so excluding them is okay for now.

Here's the log entry, directory names in <> brackets are not actual names ofcourse.

`rsync errors: rsync: read errors mapping "/Users/<admin>/Library/Mobile Documents.<someintegernumber>/com~apple~TextInput/Dictionaries/.baseline/UserDictionary/<somelongstringendingwith=>/baseline.zip": Bad file descriptor (9) rsync: read errors mapping "/Users/<admin>/Library/Mobile Documents.<someintegernumber>/com~apple~TextInput/Dictionaries/.baseline/UserDictionary/<somelongstringendingwith=>baseline.zip": Bad file descriptor (9) ERROR: Users/<admin>/Library/Mobile Documents.<someintegernumber>/com~apple~TextInput/Dictionaries/.baseline/UserDictionary/<somelongstringendingwith=>/baseline.zip failed verification -- update discarded.`

**Comment by burdges** [comment]
I've never noticed a `Mobile*Documents*` folder, but presumably `/.MobileBackups` should be excluded. 

Just a few other directories that should probably be excluded : 
    .dbfseventsd
    .fseventsd

Also an [ancient page](http://nicolasgallagher.com/mac-osx-bootable-backup-drive-with-rsync/) lists these additional exclusions : 
    /afs*
    /private/var/run/*
    /private/var/spool/postfix/* 
    /Previous Systems.localized
